// 用來把 js 轉成 str
import fs from 'fs';
import path from 'path';

const root = process.cwd();
const enginePath = path.join(root, 'packages/engine/engine.js');
const evalexprPath = path.join(root, 'packages/engine/evalexpr.js');
const statePath = path.join(root, 'packages/engine/state.js');
const outputPath = path.join(root, 'packages/cli/assets_manifest.js');

function getSource(filePath) {
    const code = fs.readFileSync(filePath, 'utf-8');
    return JSON.stringify(code);
}

const manifest = `
// auto-generated by prep.js
export const ENGINE_CODE = ${getSource(enginePath)};
export const EVALEXPR_CODE = ${getSource(evalexprPath)};
export const STATE_CODE = ${getSource(statePath)};
`;

fs.writeFileSync(outputPath, manifest);
console.log('Assets manifest updated.');