import fs from "fs"
import path from "path"
import { tokenize } from "../compiler/lexer.js"
import { parse } from "../compiler/parser.js"
import { templateHTML } from "../cli/index.html.js"
import { ENGINE_CODE, STATE_CODE } from './assets_manifest.js';

// ---0. init
const root = process.cwd();
fs.rmSync(path.join(root, "dist"), { recursive: true, force: true });

const configPath = path.join(root, "config.json");
if (!fs.existsSync(configPath)) throw new Error("Config file not found.")
const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));

// ---1. parse .st files
const gameDir = path.join(root, "game");
function findSTFiles(dir) {
    let results = [];

    for (const file of fs.readdirSync(dir)) {
        const srcPath = path.join(dir, file);
        const stat = fs.statSync(srcPath);
        if (stat.isDirectory()) {
            results = results.concat(findSTFiles(srcPath));
        } else if (file.endsWith(".st")) {
            results.push(srcPath);
        }
    }

    return results;
}
const stFiles = findSTFiles(gameDir);
if (stFiles.length === 0) throw new Error("No .st files found.");
let passages = {};
for (const file of stFiles) {
    const source = fs.readFileSync(file, "utf-8");
    const tokens = tokenize(source);
    const parsed = parse(tokens);
    if (!parsed || typeof parsed !== "object") throw new Error(`Failed to parse ${file}`);
    passages = {...passages,...parsed };
}

// ---2. passages to js
export function passagesToJS(passages) {
    let output = `/** Generated by SaltTriangle Build Tool **/\n`;
    output += `window.passages = {\n`;

    for (const [id, passage] of Object.entries(passages)) {
        output += `  "${id}": {\n`;
        output += `    id: ${JSON.stringify(passage.id)},\n`;
        output += `    layout: ${JSON.stringify(passage.layout)},\n`;
        output += `    tags: ${JSON.stringify(passage.tags)},\n`;
        output += `    onEnter: ${passage.onEnter ? JSON.stringify(passage.onEnter) : "null"},\n`;
        output += `    afterRendered: ${passage.afterRendered ? JSON.stringify(passage.afterRendered) : "null"},\n`;
        output += `    onExit: ${passage.onExit ? JSON.stringify(passage.onExit) : "null"},\n`;
        
        output += `    slots: {\n`;
        for (const [slotName, nodes] of Object.entries(passage.slots)) {
            output += `      "${slotName}": [\n`;
            nodes.forEach(node => {
                output += `        ${serializeNode(node)},\n`;
            });
            output += `      ],\n`;
        }
        output += `    }\n`;
        output += `  },\n`;
    }

    output += `};`;
    return output;
}
function serializeNode(node) {
    // deal link content
    if (node.type === 'LINK') {
        return `{ 
            type: "LINK", 
            value: ${JSON.stringify(node.value)}, 
            nextPassage: ${JSON.stringify(node.nextPassage)}, 
            content: ${JSON.stringify(node.content)} 
        }`;
    }
    
    return JSON.stringify(node);
}

// ---3. inline layouts
const layoutSrc = path.join(root, "layouts");
function loadLayouts(src) {
    const layouts = {}
    const items = fs.readdirSync(src);
    for (const item of items) {
        const fullPath = path.join(src, item);
        const stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
            Object.assign(layouts, loadLayouts(fullPath));
        } else if (item.endsWith(".html")) {
            const layoutKey = path.basename(item, ".html");
            const content = fs.readFileSync(fullPath, "utf-8");
            layouts[layoutKey] = content;
        }
    }
    return layouts;
}
if (!fs.existsSync(layoutSrc)) throw new Error("Layouts not found")
const layoutsData = loadLayouts(layoutSrc)
let layoutsScript = "window.STLayouts = {\n";
for (const [key, value] of Object.entries(layoutsData)) {
    layoutsScript += `  "${key}": ${JSON.stringify(value)},\n`;
}
layoutsScript += "};";

// ---4. inline module
const moduleDir = path.join(root, "module");
let jsInline = "";
let cssInline = "";

function collectModules(src) {
    if (!fs.existsSync(src)) return;

    for (const file of fs.readdirSync(src).sort()) {
        const fullPath = path.join(src, file);
        const stat = fs.statSync(fullPath);
        if (stat.isDirectory()) {
            collectModules(fullPath);
        } else {
            const content = fs.readFileSync(fullPath, "utf-8");
            if (file.endsWith(".js")) jsInline += `\n<script>${content}</script>\n`;
            if (file.endsWith(".css")) cssInline += `\n<style>${content}</style>\n`;
        }
    }
}
collectModules(moduleDir);

// ---5. copy assets
const assetsSrc = path.join(root, "assets");
const assetsDst = path.join(root, "dist/assets");
function copyAssets(src, dest) {
    if (!fs.existsSync(src)) return;
    fs.mkdirSync(dest, { recursive: true });

    for (const file of fs.readdirSync(src)) {
        const srcPath = path.join(src, file);
        const destPath = path.join(dest, file);
        const stat = fs.statSync(srcPath);
        if (stat.isDirectory()) {
            copyAssets(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    };
};
if (fs.existsSync(assetsSrc)) {
    copyAssets(assetsSrc, assetsDst);
}

// ---e.check 
// check if all layouts used in passages exist
const layoutsSet = new Set();
for (const p of Object.values(passages)) {
    layoutsSet.add(p.layout);
}
for (const layout of layoutsSet) {
    if (!(layout in layoutsData)) throw new Error(`layout: ${layout} not found.`)
}

// ---f. index.html 
let html = templateHTML
html = html.split("{{TITLE}}").join(config.title);
html = html.split("{{ICON}}").join(config.icon ? `<link rel="icon" href="${config.icon}">` : "");
html = html.split("{{CSS}}").join(cssInline);
html = html.split("{{ENGINE}}").join("<script type='module'>" + ENGINE_CODE + ";window.__EngineReady = true" + "</script>");
html = html.split("{{STATE}}").join("<script>" + STATE_CODE + "</script>");
html = html.split("{{LAYOUTS}}").join("<script>" + layoutsScript + "</script>");
html = html.split("{{PASSAGES}}").join("<script>" + passagesToJS(passages) + "</script>");
html = html.split("{{SCRIPTS}}").join(jsInline);

fs.writeFileSync(path.join(root, "dist/index.html"), html);